### ISSUE TITLE
Documentation is not being generated

### ISSUE THREAD

**Issue by singla-shivam** [denoland/doc_website#110] opened 2020-05-30 16:46 UTC
Documentation for [fae](https://doc.deno.land/https/deno.land/x/fae/mod.ts) opened 2 or 3 times. After that it is showing **A internal server error occured while generating the documentation.**

Module - https/deno.land/x/fae/mod.ts

**Comment by kennanseno** [comment] 2020-05-31 20:37
similar to https://github.com/denoland/doc_website/issues/96

**Comment by bartlomieju** [comment] 2020-09-04 19:38
CC @lucacasonato

**Comment by lucacasonato** [comment] 2020-09-04 19:43
Duplicate of #96

**Closed by lucacasonato** 2020-09-04 19:44 UTC
