### ISSUE TITLE
Scrolling inside the content div

### ISSUE THREAD

**Issue by JipFr** [denoland/doc_website#78] opened 2020-04-30 20:53 UTC
On the documentation page on doc.deno.land (for example, [this](https://doc.deno.land/https/deno.land/std/http/mod.ts)) the main content is inside a wrapper div, which has an overflow rule, leading to scrolling inside the div instead of the body.

Would it be possible to have this converted to make it so the sidebar and header are sticky and the content scrolls like you normally would instead of in a nested div? This would make it so you could also scroll when your mouse is on the header, and also makes it so the site is more accessible on iOS.

**Comment by bartlomieju** [comment] 2020-05-01 10:32
CC @lucacasonato

**Comment by lucacasonato** [comment] 2020-05-01 10:36
Yup, its terrible. I was just getting really fed up with other options so I fell back to absolute. I’ll definitely fix this. Duplicate of #39.

**Comment by JipFr** [comment] 2020-05-01 11:01
Ah, I didn’t think that issue included the scrolling as well.

**Closed** 2020-05-03 18:24 UTC
